// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PhaserWrapper from "./phaserWrapper";

function makeScene(prim0, prim1, prim2, prim3) {
  return PhaserWrapper.createScene(prim0, prim1, prim2, prim3);
}

function makeGame(prim) {
  return PhaserWrapper.createGame(prim);
}

function addLogo(prim) {
  return PhaserWrapper.addLogo(prim);
}

function addParticles(prim) {
  return PhaserWrapper.createParticles(prim);
}

export {
  makeScene ,
  makeGame ,
  addLogo ,
  addParticles ,
}
/* ./phaserWrapper Not a pure module */
