// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PhaserWrapper from "./phaserWrapper";

function makeScene(prim0, prim1, prim2, prim3) {
  return PhaserWrapper.createScene(prim0, prim1, prim2, prim3);
}

function makeGame(prim) {
  return PhaserWrapper.createGame(prim);
}

var x = 5;

export {
  x ,
  makeScene ,
  makeGame ,
}
/* ./phaserWrapper Not a pure module */
